**********  Task B **********  Data ********** 
clear
cd /Users/stanza/documents/github/etc4420
set more off
capture log close
log using Task_B.log,replace
use "SS hilda.dta", replace

//Introduction and data cleaning.
//We are insterested in the factors determining the weekly wage for the whole 
//Australian population, using the wage data of those who are currently working.
//First, we check the data by looking at the summary statistics. 
sum
///In this dataset, we have variables relating personal earnings, age, gender,
//current employment status, eduction level, number of dependent children,
//having concenssion card or not, self-reported health, and marital status.
//All variables are discrete or dummy variables except income related variables.

//There are a lot of missing values in logincome, which is caused by the zero
//in disposable income. There are also missing values in 'lfp' because many
//people did not respond to the employment status question in the survey. Same 
//with 'esempst' which is a more detailed employment status variable, 'scage'
//which indicating age group,  'male', 'edhigh' which is the highest education 
//level, 'concession' and 'married'.
//Since we want to study the weekly wage, we will use 'wscei' as our dependent 
//variable. So we check its histogram.
histogram wscei
//From this histogram we can see 'wscei' is not normally distributed, actually 
//its distribution looks like exponential distribution, where it may be better 
//to do log transformation to it and then analyse. 
gen logwscei=log(wscei)
histogram logwscei
//Hence, we generated a new variable named logwscei which is the log(wscei).
//And we can see its histogram looks much more like normal than wscei.
//But now we have much less observations since a lot of missing values are 
//generated by this log-transformation. This could be a problem for Tobit model.
//Therefore, we will follow the instruction in our exercise first and talk
//about this issue later on.
//Also we want to keep as many observations as we could, 
//so we will not use any employment status related variables in this dataset 
//directly. Instead, we will generate a new dummy variable called 'working' 
//indicating if a person is working or not given the value of his/her 'wscei'
//as our selection variable.
//We will also use 'male', detailed 'age' band variables (the youngest group is
//the reference level), and four 'education' levels (less than year 12 will be 
//the reference) as the determinants for the outcome equation. Because age and
//education are obviously have strong correlation with one's wage. To confirm,
//we do cross tabulation for age and wage.
tab scage, summarize(wscei)
//From this cross tabulation, we can see strong relationship between 'age' and 
//'wscei'. Wage is increasing with age before 45-54, and dreasing with it after.
//Unfortunately, gender is assumed to still have some impact as well.
//'Marital status' and 'dependent children' will be included in the selection 
//equation as extra IVs. Because these two factors will definitely have impact
//on one person's employment status but assumed to be irrelevant to one's wage.

gen working = wscei != 0
lab var working "=1 for working people, =0 otherwise"

//Check the new variable by looking at its summary statistics.
tab working
//In this subset, there are 8216 working people indicated by 'working', while 
//8216 non-working people. This 'working' variable maybe not necessarily accurate
//given the way we generated it. So we check the cross tabulation of it with 
//other employment status variables.
tab esbrd working
//We can see there are some mismatch between the two, since some 'employee' 
//indicated by 'esbrd' are grouped as 0 in 'working'. This may because some 
//employees did not report the weekly wage. As far as our assignment concerned,
//we will assume the working status are mostly correct specified and use it in 
//our further analysis.

**********  Task B **********  Questions ********** 

set seed 27886913
sample 12000, count

//Check data again after sampling.
sum
//Random sampling works fine.

//Estimate a Heckman sample selection model using Two-step Heckit Estimator
//Task B Question 1

heckman wscei age1819 age2021 age2224 age2534 age3544 age4554 age5564 age6574 /*
*/age75above male bachabv dipcert year12, select(working =age1819 age2021 /*
*/age2224 age2534 age3544 age4554 age5564 age6574  age75above male bachabv /*
*/dipcert year12 married depkid) twostep
estimate store heckman_2step

//Estimate a Heckman sample selection model using MLE
//Task B Question 1

heckman wscei age1819 age2021 age2224 age2534 age3544 age4554 age5564 age6574 /*
*/age75above male bachabv dipcert year12, select(working =age1819 age2021 /*
*/age2224 age2534 age3544 age4554 age5564 age6574  age75above male bachabv /*
*/dipcert year12 married depkid)

estimate store heckman_mle
estimate table heckman_2step heckman_mle
//As we can see, the estimated coefficients are very different for these two
//methods in the outcome equation. I think the reason for that is what we 
//mentioned above, the normal assumption is clearly violated in this case, 
//so the estimated standard deviations are very large. Hence the estimates are
//very sensitive to the change in estimating methods.

//What's more, we can see the estimated rho is negative. Intuitively, it is more
//reasonable to be positive. The residuals in the outcome equation and the 
//selection equation maybe positively correlted. Because the unobserved factors
//that make people working are more likely to also make people earn more.
//I think this may due to the lack of good IVs. Or it could be x variables take
//too much information in residuals which over-compensated the issue. Or maybe
//our dataset is not a good one.

//Estimate the marginal effects for E('wscei') and E('wscei'|working=1) based on 
//the MLE model above.
//Task B Question 2

//marginal effects at means for E('wscei'), unconditional ME
quietly heckman wscei age1819 age2021 age2224 age2534 age3544 age4554 age5564 age6574 /*
*/age75above male bachabv dipcert year12, select(working =age1819 age2021 /*
*/age2224 age2534 age3544 age4554 age5564 age6574  age75above male bachabv /*
*/dipcert year12 married depkid)
margins, dydx(*) atmean

//marginal effects at means for E('wscei'|working=1), conditional ME
margins, dydx(*) predict(ycond) atmean
//Continued from our previous discussion about the negative rho, we can see 
//some weird results from these two marginal effects. For instance, the marginal 
//effect of achieving bachelor degree is larger on the working group which is 
//582.4258 while 558.4575 on the whole population. In reality, we think
//education should have bigger marginal effect on the whole population than 
//the working people since employees are often have higher education level than
//unemployees. This result is caused by the fact that our estimated rho is
//negative.

//Estimate a Tobit model for 'wscei' with a left censoring point of wscei=0.
//Task B Question 3
//We use all variables as explanatory variables including married and depkid.

tobit wscei age1819 age2021 age2224 age2534 age3544 age4554/*
*/ age5564 age6574 age75above male bachabv dipcert year12 married depkid, ll

//Unconditional marginal effects at means for E('wscei')
margins, dydx(*) atmean
//The β coefficients themselves measure how the unobserved variable y* changes 
//with respect to changes in the regressors. That's why these marginal effects
//are the same with our coefficient estimates in Tobit model.


//conditional marginal effects at means for E('wscei'|working=1)
margins, dydx(*) predict(ystar(0,.)) atmean

//The estimates for ME of the independent variables from Tobit are smaller 
//than from Heckman

//Tobit treats zero wage as zero while the Heckman model considers zero 
//wage as unobserved.
//Tobit is used if it is a censored data set, while Heckman is used if it is a 
//self-selected data set
//Decision on which model to use depends largely on the reasons why the zeros 
//arise
//Whether it is the result of a choice, or is it that only values below 0 are 
//unobserved, or could come 
//unobserved values also be above 0


log close 








